//
//  ASCII.swift
//  
//
//  Created by Adrian McDaniel on 11/28/16.
//
//

import Foundation
import Darwin

func clearScreen() {
    Process.launchedProcess(launchPath: "/usr/bin/clear", arguments: []).waitUntilExit()
}

clearScreen()

print("ooo                 ooo  oooooooooo  ooo             ooooo      ooooo       oooooooooooooooo  oooooooooo")
print("ooo                 ooo  oooooooooo  ooo           ooo        ooo   ooo     oooooooooooooooo  oooooooooo")
print(" ooo     ooooo     ooo   ooo         ooo         ooo        ooo       ooo   ooo    oo    ooo  ooo")
print("  ooo   ooo ooo   ooo    oooooo      ooo        ooo        ooo         ooo  ooo    oo    ooo  oooooo")
print("   ooo ooo   ooo ooo     oooooo      ooo        ooo        ooo         ooo  ooo    oo    ooo  oooooo")
print("    ooooo     ooooo      ooo         ooo         ooo        ooo       ooo   ooo    oo    ooo  ooo")
print("     ooo       ooo       oooooooooo  oooooooooo    ooo        ooo   ooo     ooo    oo    ooo  oooooooooo")
print("      o         o        oooooooooo  oooooooooo      ooooo      ooooo       ooo    oo    ooo  oooooooooo")

sleep(3)
clearScreen()

print("                                          ooooooooo   ooo")
print("                                             ooo     oo oo ")
print("                                              o     o     o")
print("                                              o     o     o")
print("                                              o      oo oo")
print("                                              o       ooo")

sleep(2)
clearScreen()




print(" ")
print(" ")
print("                                        ~~~~~~~~~~  ~   ~  ~~~~~")
print("                                             ~~    ~   ~  ~")
print("                                            ~~    ~~~~~  ~~~~")
print("                                           ~~    ~   ~  ~  ")
print("                                          ~~    ~   ~  ~~~~~")
print("                                    ****** ******  *****  ****    ***")
print("                                    ****** **  ** *** *** ****    **")
print("                                      **   **  ** **   ** ** **   **")
print("                                      **   ****** **   ** **  **  **")
print("                                      **   ** **  **   ** **   ** **")
print("                                    ****** **  ** *** *** **    ****")
print("                                    ****** **   ** *****  **     ***")

print("                                    ***  ***   *    ******  *****")
print("                                     **  **   ***   **  **  **  **")
print("                                      ****   ** **  **  **  **   **")
print("                                       **   **   ** ******  **   **")
print("                                       **   ******* ** **   **   **")
print("                                       **   **   ** **  **  **  **")
print("                                       **   **   ** **   ** *****")

sleep(4)
clearScreen()

print("            |     |   |||   ||     || ||||||      |||   ||||||    ||||||| |     | ||||||")
print("            |     |  |   |  | |   | | |          |   |  |            |    |     | |")
print("            |     | |     | |  | |  | |         |     | |            |    |     | |")
print("            |-----| |     | |   |   | |___      |     | |___         |    |-----| |---")
print("            |     | |     | |       | |         |     | |            |    |     | |")
print("            |     |  |   |  |       | |          |   |  |            |    |     | |")
print("            |     |   |||   |       | ||||||      |||   |            |    |     | ||||||")

sleep(3)
clearScreen()

print("                                  ----------------------------------")
print("                                 |  ------------------------------  |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 |  ------------------------------  |")
print("                                 |                **                |")
print("                                 |               *  *               |")
print("                                 |                **                |")
print("                                  ----------------------------------")

sleep(1)
clearScreen()

print("                                  ----------------------------------")
print("                                 |  ------------------------------  |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |         *   $$     $         | |")
print("                                 |  ------------------------------  |")
print("                                 |                **                |")
print("                                 |               *  *               |")
print("                                 |                **                |")
print("                                  ----------------------------------")

sleep(1)
clearScreen()


print("                                  ----------------------------------")
print("                                 |  ------------------------------  |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |         *   $$     $$        | |")
print("                                 | |            $  $   $          | |")
print("                                 | |         $ $    $   $         | |")
print("                                 | |         $  $  $     $        | |")
print("                                 | |         $   $$    $$         | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 |  ------------------------------  |")
print("                                 |                **                |")
print("                                 |               *  *               |")
print("                                 |                **                |")
print("                                  ----------------------------------")

sleep(1)
clearScreen()


print("                                  ----------------------------------")
print("                                 |  ------------------------------  |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |         *   $$     $$        | |")
print("                                 | |            $  $   $          | |")
print("                                 | |         $ $    $   $         | |")
print("                                 | |         $  $  $     $        | |")
print("                                 | |         $   $$    $$         | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |       $$$ $$$$  $$$ $   $    | |")
print("                                 | |      $    $  $  $   $   $    | |")
print("                                 | |     $     $ $$  $$  $ $ $    | |")
print("                                 | |      $    $  $  $   $ $ $    | |")
print("                                 |  ------------------------------  |")
print("                                 |                **                |")
print("                                 |               *  *               |")
print("                                 |                **                |")
print("                                  ----------------------------------")

sleep(1)
clearScreen()

print("                                  ----------------------------------")
print("                                 |  ------------------------------  |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |         *   $$     $$        | |")
print("                                 | |            $  $   $          | |")
print("                                 | |         $ $    $   $         | |")
print("                                 | |         $  $  $  $  $        | |")
print("                                 | |         $   $$    $$         | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |       $$$ $$$$  $$$ $   $    | |")
print("                                 | |      $    $  $  $   $   $    | |")
print("                                 | |     $     $ $$  $$  $ $ $    | |")
print("                                 | |      $    $  $  $   $ $ $    | |")
print("                                 | |       $$$ $   $ $$$ $$$$$    | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 | |                              | |")
print("                                 |  ------------------------------  |")
print("                                 |                **                |")
print("                                 |               *  *               |")
print("                                 |                **                |")
print("                                  ----------------------------------")


print("                                                            Adrian McDaniel")
print("                                                                       2016")

print()



